### **Array Creation and Array Elements**

In [1]:
from numpy import linspace

x = linspace(0, 2, 3)

x

array([0., 1., 2.])

In [2]:
type(x)

numpy.ndarray

In [3]:
type(x[0])

numpy.float64

In [5]:
sum_elements = x[0] + x[1] + x[2]
sum_elements

np.float64(3.0)

In [7]:
product_2_elements = x[1] * x[2]
product_2_elements

np.float64(2.0)

In [8]:
x[0] = 5.0      # overwrite previeous value
x

array([5., 1., 2.])

In [ ]:
from numpy import zeros

x = zeros(3, int)       # get array with integer zeros

x

array([0, 0, 0])

In [ ]:
y = zeros(3)            # get array with floating point zeros

y

array([0., 0., 0.])

In [12]:
y[0] = 0.0; y[1] = 1.0; y[2] = 2.0  # overwrite

y

array([0., 1., 2.])

In [13]:
len(y)

3

In [14]:
from numpy import array

x = array([0, 1, 2])    # get aray with integers

x

array([0, 1, 2])

In [15]:
x = array([0., 1., 2.])     # get array with real numbers

x

array([0., 1., 2.])

### **Indexing an Array from the End**

In [16]:
x[-1]

np.float64(2.0)

In [17]:
x[-2]

np.float64(1.0)

In [18]:
x[-3]

np.float64(0.0)

### **Copying an Array**

In [19]:
y = x

y

array([0., 1., 2.])

In [20]:
y[0] = 10.0

y

array([10.,  1.,  2.])

In [21]:
x

array([10.,  1.,  2.])

In [22]:
from numpy import copy

x = linspace(0, 2, 3)

y = copy(x)

y

array([0., 1., 2.])

In [ ]:
y[0] = 10.0

y       # changed

array([10.,  1.,  2.])

In [25]:
x       # unchanged

array([0., 1., 2.])

### **Slicing an Array**

In [26]:
from numpy import linspace

x = linspace(11, 16, 6)

x

array([11., 12., 13., 14., 15., 16.])

In [27]:
y = x[1:5]

y

array([12., 13., 14., 15.])

In [28]:
y[0] = -1.0

y

array([-1., 13., 14., 15.])

In [29]:
x

array([11., -1., 13., 14., 15., 16.])

### **Two-Dimensional Arrays and Matrix Computations**

In [ ]:
import numpy as np

I = np.zeros((3, 3))    # create matrix

I

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
type(I)

numpy.ndarray

In [36]:
I[0, 0] = 1.0; I[1, 1] = 1.0; I[2, 2] = 1.0     # Identity matrix

x = np.array([1.0, 2.0, 3.0])       # create vector

y = np.dot(I, x)                    # computes matrix-vector product

y

array([1., 2., 3.])

In [ ]:
import numpy as np

I = np.eye(3)       # create identity matrix

I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
type(I)

numpy.ndarray

In [40]:
I = np.matrix(I)    # convert to matrix object

type(I)

numpy.matrix

In [42]:
x = np.array([1., 2., 3.,])

x

array([1., 2., 3.])

In [ ]:
x = np.matrix(x)    # convert to matrix object

x = x.transpose()   # convert to column vector

x

matrix([[1.],
        [2.],
        [3.]])

In [44]:
y = I * x

y

matrix([[1.],
        [2.],
        [3.]])