In [1]:
import random

a = 1; b = 6
r1 = random.randint(a, b)   # first die
r2 = random.randint(a, b)   # second die

print('the dice gave: {:d} and {:d}'.format(r1, r2))

the dice gave: 5 and 6


In [2]:
import random

random.seed(10)

random.randint(1, 6)

5

In [3]:
random.randint(1, 6)

1

In [4]:
import random

x = random.random()         # draw float from [0, 1] assign to x

y = random.uniform(10, 20)  # ...float from [10, 20] assign to y

print('x = {:g}, y = {:g}'.format(x, y))

x = 0.428889, y = 15.7809


In [5]:
import numpy as np

np.random.randint(1, 6, 4)  # ...4 integers from [1, 6]

array([5, 4, 1, 4])

In [6]:
np.random.random(4)         # ...4 floats from [0, 1]

array([0.52282805, 0.97277713, 0.25568704, 0.57923819])

In [7]:
np.random.uniform(10, 20, 4)    # ...4 floats from [10, 20]

array([13.85700383, 16.0577985 , 19.62614195, 16.04207986])

In [8]:
import numpy as np

a = np.array([1, 2, 3, 4])

np.random.shuffle(a)

a

array([3, 2, 1, 4])